version: '3.8'

services:
  fastapi_server:
    container_name: fastapi_server
    # image: jrtec/fastapi-alembic-sqlmodel-async:latest
    build: ./backend
    restart: always
    #command: "sh -c 'alembic upgrade head && python app/initial_data.py && gunicorn -w 3 -k uvicorn.workers.UvicornWorker app.main:app  --bind 0.0.0.0:8008 --preload --log-level=debug --timeout 120'"
    command: "sh -c 'alembic upgrade head && uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8008'"
    volumes:
      - ./backend/app:/code
    expose:
      - 8008
    env_file: ".env"
    depends_on:
      - database
    links:
      - caddy_reverse_proxy:storage.localhost
  
  database:
    # image: bitnami/postgresql:13.3.0
    image : arm64v8/postgres
    restart: always
    container_name: database
    env_file: ".env"
    user: root
    volumes:
      - ./db_docker:/bitnami/postgresql
      - ./create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
    ports:
      - 5454:5432 # Remove this on production
    expose:
      - 5432
    environment:
      - POSTGRES_USERNAME=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DATABASE=${DATABASE_NAME}
      - POSTGRES_HOST_AUTH_METHOD= "trust"

      
  redis_server:
    container_name: redis_server
    image: "redis:alpine"
    restart: always
    expose:
      - 6379
    env_file: .env


  caddy_reverse_proxy:
    container_name: caddy_reverse_proxy
    image: caddy:alpine
    restart: always
    ports:
      - 88:88
      - 8088:8088
      - 443:443
    environment:
      - EXT_ENDPOINT1=${EXT_ENDPOINT1}
      - LOCAL_1=${LOCAL_1}
      - LOCAL_2=${LOCAL_2}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./static:/code/static
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: