"""empty message

Revision ID: c8ba135f0d30
Revises: f2348f38dedd
Create Date: 2024-06-15 14:27:56.616766

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'c8ba135f0d30'
down_revision = 'f2348f38dedd'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ArtistGoodsDeal',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_image_list', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('artist_goods_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('company_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('artist_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['artist_goods_id'], ['ArtistGoods.id'], ),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['Company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ArtistGoodsDeal_id'), 'ArtistGoodsDeal', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ArtistGoodsDeal_id'), table_name='ArtistGoodsDeal')
    op.drop_table('ArtistGoodsDeal')
    # ### end Alembic commands ###