"""empty message

Revision ID: 2745d398ac35
Revises: 8a74e6b255d4
Create Date: 2024-06-30 01:21:02.548315

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2745d398ac35'
down_revision = '8a74e6b255d4'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ArtistGoodsDeal_payment_id_fkey', 'ArtistGoodsDeal', type_='foreignkey')
    op.drop_column('ArtistGoodsDeal', 'payment_id')
    op.add_column('Payment', sa.Column('artist_goods_deal_id', sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.drop_constraint('Payment_artist_goods_id_fkey', 'Payment', type_='foreignkey')
    op.create_foreign_key(None, 'Payment', 'ArtistGoodsDeal', ['artist_goods_deal_id'], ['id'])
    op.drop_column('Payment', 'artist_goods_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Payment', sa.Column('artist_goods_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Payment', type_='foreignkey')
    op.create_foreign_key('Payment_artist_goods_id_fkey', 'Payment', 'ArtistGoods', ['artist_goods_id'], ['id'])
    op.drop_column('Payment', 'artist_goods_deal_id')
    op.add_column('ArtistGoodsDeal', sa.Column('payment_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('ArtistGoodsDeal_payment_id_fkey', 'ArtistGoodsDeal', 'Payment', ['payment_id'], ['id'])
    # ### end Alembic commands ###