"""empty message

Revision ID: 8d3f193ca64e
Revises: bdb810452e49
Create Date: 2024-05-17 14:33:53.092634

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '8d3f193ca64e'
down_revision = 'bdb810452e49'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'follower_count')
    op.drop_column('User', 'following_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('following_count', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('follower_count', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###