"""empty message

Revision ID: 66f0b5251102
Revises: fa1345721e66
Create Date: 2024-06-09 19:22:40.284582

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '66f0b5251102'
down_revision = 'fa1345721e66'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'favorite_category',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'favorite_category',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###