"""empty message

Revision ID: 5307d4f68739
Revises: 82ffc9fd5fa4
Create Date: 2024-06-11 18:30:18.037543

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '5307d4f68739'
down_revision = '82ffc9fd5fa4'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('Company', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Company', 'content')
    op.drop_column('Artist', 'content')
    # ### end Alembic commands ###