"""empty message

Revision ID: 513471c63cb1
Revises: 899488c28863
Create Date: 2024-05-28 12:07:13.984816

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '513471c63cb1'
down_revision = '899488c28863'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('ArtistGoods', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ArtistGoods', 'duration')
    op.drop_column('Artist', 'description')
    # ### end Alembic commands ###